const mongoose = require("mongoose");
const { Schema } = mongoose;

const TemplateSchema = new mongoose.Schema({
  templateId: { type: String },
  navbar: {
    logo: String,
    brand: String,
    link1: String,
    link2: String,
    link3: String,
    link4: String,
    link5: String,
    link6: String,
    link7: String,
    buttonText1: String,
    buttonText2: String,

    styles: {
      backgroundColor: String,
      color: String,
      fontFamily: String,
    },
  },
  hero: {
    title1: String,
    title2: String,
    summary1: String,
    summary2: String,
    summary3: String,
    summary4: String,
    span1: String,
    span2: String,
    buttonText1: String,
    buttonText2: String,
    backgroundImage1: String,
    backgroundImage2: String,
    backgroundImage3: String,
    styles: {
      color: String,
      fontFamily: String,
    },
  },
  aboutUs: {
    title1: String,
    title2: String,
    text1: String,
    text2: String,
    buttonText1: String,
    buttonText2: String,
    image1: String,
    image2: String,
    image3: String,
    image4: String,
    image5: String,
    styles: {
      backgroundColor: String,
      color: String,
      fontFamily: String,
    },
  },
  Vision: {
    visiomheader: String,
    visionsummary: String,
    impactheader: String,
    impactsummary: String,
    missionheader: String,
    missionsummary: String,
    styles: {
      backgroundColor: String,
      color: String,
      fontFamily: String,
    },
  },
  Statistics: {
    section1header: String,
    section1paragraphy: String,
    section1span: String,
    section1icon: String,
    section2header: String,
    section2paragraphy: String,
    section2span: String,
    section2icon: String,
    section3header: String,
    section3paragraphy: String,
    section3span: String,
    section3icon: String,
    section4header: String,
    section4paragraphy: String,
    section4span: String,
    section4icon: String,
  },
  Patrners: {
    sectionImage1: String,
    section1header: String,
    sectionImage2: String,
    section2header: String,
    sectionImage3: String,
    section3header: String,
    sectionImage4: String,
    section4header: String,
    buttonText1: String,
    buttonText2: String,
  },
  Events: {
    heading: String,
    summary: String,
    sectionImage1: String,
    section1header: String,
    section1paragraphy: String,
    buttonText1: String,
    sectionImage2: String,
    section2header: String,
    section2paragraphy: String,
    buttonText2: String,
    sectionImage3: String,
    section3header: String,
    section3paragraphy: String,
    buttonText3: String,
    sectionImage4: String,
    section4header: String,
    section4paragraphy: String,
    buttonText4: String,
  },
  Gallery: {
    image1: String,
    summary1: String,
    image2: String,
    summary2: String,
    image3: String,
    summary3: String,
    image4: String,
    summary4: String,
    image5: String,
    summary5: String,
    image6: String,
    summary6: String,
  },
  LargeCta: {
    image1: String,
    header1: String,
    image2: String,
    header2: String,
    header3: String,
    summary1: String,
    summary2: String,
    buttonText1: String,
    buttonText2: String,
  },
  Team: {
    image1: String,
    header1: String,
    summary1: String,
    image2: String,
    header2: String,
    summary2: String,
    image3: String,
    header3: String,
    summary3: String,
    image4: String,
    header4: String,
    summary4: String,
  },
  Blog: {
    image1: String,
    header1: String,
    summary1: String,
    date1: String,
    author1: String,
    content1: String,
    buttonText1: String,
    image2: String,
    header2: String,
    summary2: String,
    date2: String,
    author2: String,
    content2: String,
    buttonText2: String,
    image3: String,
    header3: String,
    summary3: String,
    date3: String,
    author3: String,
    content3: String,
    buttonText3: String,
    image4: String,
    header4: String,
    summary4: String,
    date4: String,
    author4: String,
    content4: String,
    buttonText4: String,
  },
  Reviews: {
    image1: String,
    header1: String,
    title1: String,
    summary1: String,
    image2: String,
    header2: String,
    summary2: String,
    title2: String,
    image3: String,
    header3: String,
    summary3: String,
    title3: String,
  },
  contactUs: {
    heading1: String,
    heading2: String,
    heading3: String,
    heading4: String,
    heading5: String,
    heading6: String,
    heading7: String,
    paragraph1: String,
    buttonText1: String,
    styles: {
      backgroundColor: String,
      color: String,
      fontFamily: String,
    },
  },
  faq: [
    {
      question: String,
      answer: String,
    },
  ],
  faqStyles: {
    backgroundColor: String,
    color: String,
    fontFamily: String,
  },
  footer: {
    logo: String,
    header: String,
    title1: String,
    title2: String,
    title3: String,
    title4: String,
    paragraph1: String,
    paragraph2: String,
    paragraph3: String,
    paragraph4: String,
    paragraph5: String,
    paragraph6: String,
    paragraph7: String,
    paragraph8: String,
    paragraph9: String,
    paragraph10: String,
    privacy: String,
    legal: String,
    footerTags: String,

    styles: {
      backgroundColor: String,
      color: String,
      fontFamily: String,
    },
  },
});

const GeneralTemplate = mongoose.model("GeneralTemplate", TemplateSchema);

module.exports = GeneralTemplate;
